ref_cl = "CVCL_0023"
use_delta_ref = true
n_pca_expr = 128
use_pca_cache = true
hidden_layers = [1024, 128, 1024]
batch_size = 256
n_epochs = 200
lr = 8.9e-04
weight_decay = 0.001
wandb_mode = "disabled"
